import {escapeHTML as esc,latestObservation,gapSegments,formatTime} from './data.js';
export const palette=['#f3c96f','#aeabff','#72d7ef','#f794aa','#a5d78c','#ff9f65','#91bfff','#e1aedf'];
export function shipSVG(type='漁船',color='#f7ce86') {
  const fishing=type==='漁船';
  return `<svg viewBox="0 0 36 52" aria-hidden="true"><path d="M18 2C12 8 8 13 8 21V44L12 48H24L28 44V21C28 13 24 8 18 2Z" fill="${color}" stroke="#062236" stroke-width="2"/><path d="M18 5V12" stroke="#e7f2f5" stroke-width="1.2"/><rect x="12" y="${fishing?25:16}" width="12" height="12" rx="2" fill="#234357" stroke="#ecf3e6" stroke-width="1"/>${fishing?'<path d="M4 20H32M4 20V32M32 20V32M18 17V25" stroke="#f8deb1" stroke-width="2"/><rect x="13" y="38" width="10" height="5" rx="1" fill="#a27743"/>':'<path d="M12 32H24M12 38H24M18 30V44" stroke="#9a743e" stroke-width="2"/>'}<path d="M10 50H26" stroke="#cee9f0" stroke-opacity=".7"/></svg>`;
}
export function shortCable(name){const codes={'Trans-Pacific Express (TPE) Cable System':'TPE','Taiwan Strait Express-1 (TSE-1)':'TSE-1','Southeast Asia-Japan Cable (SJC)':'SJC','Southeast Asia-Japan Cable 2 (SJC2)':'SJC2','New Cross Pacific (NCP) Cable System':'NCP','Pacific Light Cable Network (PLCN)':'PLCN','Asia Pacific Gateway (APG)':'APG','Taiwan-Matsu No.4':'臺馬四號'};return codes[name]||name.match(/\(([^)]+)\)/)?.[1]||name;}
export class OceanMap {
  constructor({onShip,onCable,onStatus}) {
    this.onShip=onShip;this.onCable=onCable;this.onStatus=onStatus;
    this.map=L.map('map',{zoomControl:false,minZoom:5,maxZoom:12,zoomSnap:.25,attributionControl:true}).setView([23.75,121],7);
    L.control.zoom({position:'topright'}).addTo(this.map);L.control.scale({position:'bottomleft',imperial:false,maxWidth:130}).addTo(this.map);
    this.bounds=[[19,117],[28,125]];this.base='moi';this.visibleCables=new Set();this.cableFeatures=[];this.cableGroups=new Map();this.cableLabels=L.layerGroup().addTo(this.map);this.shipGroup=L.layerGroup().addTo(this.map);this.trackGroup=L.layerGroup().addTo(this.map);this.fixGroup=L.layerGroup().addTo(this.map);this.grid=L.layerGroup().addTo(this.map);this.places=L.layerGroup().addTo(this.map);this.layerFlags={ships:true,tracks:true,fixes:true,grid:true,labels:true};
    this.map.createPane('reliefPane');this.map.getPane('reliefPane').style.zIndex=210;
    this.map.createPane('encPane');this.map.getPane('encPane').style.zIndex=250;
    this.basemaps={moi:L.imageOverlay('./data/moi-relief.png',this.bounds,{pane:'reliefPane',className:'relief-image',attribution:'© 內政部 多維度海域資訊服務平臺'}),gebco:L.imageOverlay('./data/gebco-relief.png',this.bounds,{pane:'reliefPane',className:'relief-image',attribution:'GEBCO Grid / BODC'})};
    Object.values(this.basemaps).forEach(layer=>layer.on('error',()=>onStatus('地形快照載入失敗，請檢查資料檔案')));
    this.basemaps.moi.addTo(this.map);
    this.enc=L.imageOverlay('./data/moi-enc.png',this.bounds,{pane:'encPane',opacity:.8,attribution:'© 內政部 ENC 圖框'});
    this.map.on('mousemove',e=>{document.getElementById('coordinates').textContent=`${e.latlng.lat.toFixed(5)}° N  /  ${e.latlng.lng.toFixed(5)}° E`;});
    this.map.on('moveend zoomend',()=>this.drawGrid());
    [[25.12,121.74,'基隆'],[25.17,121.45,'淡水'],[23.58,119.58,'澎湖'],[22.62,120.28,'高雄'],[22.34,120.89,'大武'],[24.04,121.61,'花蓮'],[23.7,120.9,'臺灣 TAIWAN']].forEach(([lat,lon,name])=>L.marker([lat,lon],{icon:L.divIcon({html:esc(name),className:'place-label',iconSize:[100,18]}),interactive:false}).addTo(this.places));
    this.home();this.drawGrid();new ResizeObserver(()=>this.map.invalidateSize()).observe(document.getElementById('map'));
  }
  home(){this.map.fitBounds([[21.3,118.3],[26.05,123.5]],{padding:[30,45]});}
  setBase(name){Object.values(this.basemaps).forEach(l=>this.map.removeLayer(l));if(this.liveLayer)this.map.removeLayer(this.liveLayer);this.base=name;if(this.basemaps[name])this.basemaps[name].addTo(this.map);document.getElementById('baseBadge').textContent=name==='moi'?'內政部 200 米海底地形 · WMS 快照':name==='gebco'?'GEBCO 全球海底地形 · WMS 快照':'純海圖背景';this.setOriginal(document.getElementById('originalColor').checked);if(document.getElementById('liveWms').checked)this.setLive(true);}
  setLive(enabled){if(this.liveLayer)this.map.removeLayer(this.liveLayer);if(!enabled){if(this.basemaps[this.base])this.basemaps[this.base].addTo(this.map);document.getElementById('wmsState').textContent='使用已驗證 WMS 快照';return;}
    if(this.base==='none'){document.getElementById('wmsState').textContent='請先選擇一個地形底圖';return;}
    const url=this.base==='moi'?'https://oceanmaps.moi.gov.tw/arcgis/services/MOI_storage/topography/MapServer/WMSServer':'https://wms.gebco.net/mapserv';
    this.liveLayer=L.tileLayer.wms(url,{layers:this.base==='moi'?'0':'GEBCO_LATEST',format:'image/png',transparent:true,version:'1.1.1',pane:'reliefPane',className:document.getElementById('originalColor').checked?'relief-original':'relief-image',attribution:this.base==='moi'?'© 內政部 WMS':'GEBCO / BODC',bounds:L.latLngBounds(this.bounds),maxZoom:12});
    let failed=false;this.liveLayer.on('tileerror',()=>{failed=true;document.getElementById('wmsState').textContent='WMS 部分請求失敗，下方保留已驗證快照';});this.liveLayer.on('load',()=>{if(!failed){document.getElementById('wmsState').textContent='WMS 圖磚已載入 · 依縮放範圍請求';document.getElementById('baseBadge').textContent=(this.base==='moi'?'內政部':'GEBCO')+' · WMS 直接介接';}});this.liveLayer.addTo(this.map);document.getElementById('wmsState').textContent='正在向官方 WMS 請求圖磚…';
  }
  setOriginal(value){document.querySelectorAll('.relief-image,.relief-original').forEach(n=>{n.classList.toggle('relief-original',value);n.classList.toggle('relief-image',!value);});}
  setFlag(name,value){this.layerFlags[name]=value;const layer={ships:this.shipGroup,tracks:this.trackGroup,fixes:this.fixGroup,grid:this.grid,labels:this.cableLabels}[name];if(value)layer.addTo(this.map);else this.map.removeLayer(layer);}
  setEnc(value){if(value)this.enc.addTo(this.map);else this.map.removeLayer(this.enc);}
  loadCables(data){this.cableFeatures=data.features;const names=['APCN-2','TPE','TSE-1','SJC','SJC2','臺馬四號','EAC-C2C'];data.features.forEach((f,i)=>{const id=f.properties.id;const color=palette[i%palette.length];f.uiColor=color;f.shortName=shortCable(f.properties.name);const group=L.geoJSON(f,{style:{color,weight:2.4,opacity:.9},onEachFeature:(feature,layer)=>{layer.bindTooltip(esc(feature.properties.name)+' · 公開概化路線',{sticky:true});layer.on('click',()=>this.selectCable(id));}});this.cableGroups.set(id,group);if(names.includes(f.shortName))this.visibleCables.add(id);});this.updateCables();}
  updateCables(){this.cableLabels.clearLayers();this.cableFeatures.forEach(f=>{const id=f.properties.id,group=this.cableGroups.get(id);if(this.visibleCables.has(id)){group.addTo(this.map);const lines=f.geometry.type==='MultiLineString'?f.geometry.coordinates:[f.geometry.coordinates];const line=lines.reduce((a,b)=>{const length=x=>x.reduce((s,p,i)=>i?s+Math.hypot(p[0]-x[i-1][0],p[1]-x[i-1][1]):s,0);return length(a)>length(b)?a:b;},[]);if(line.length){const a=line[0],b=line.at(-1);L.marker([(a[1]+b[1])/2,(a[0]+b[0])/2],{icon:L.divIcon({className:'cable-name-marker',html:`<span class="cable-label" style="--cable-color:${f.uiColor}">${esc(f.shortName)}</span>`,iconSize:[85,20]}),keyboard:true,title:f.properties.name}).on('click',()=>this.selectCable(id)).addTo(this.cableLabels);}}else this.map.removeLayer(group);});this.highlightCable();document.getElementById('visibleCableCount').textContent=`${this.visibleCables.size} / ${this.cableFeatures.length} 顯示`;}
  selectCable(id){this.selectedCable=id;this.visibleCables.add(id);this.updateCables();this.onCable(this.cableFeatures.find(f=>f.properties.id===id));}
  highlightCable(){this.cableGroups.forEach((group,id)=>{group.setStyle({weight:id===this.selectedCable?5:2.4,opacity:this.selectedCable?(id===this.selectedCable?1:.45):.9});if(id===this.selectedCable)group.bringToFront();});}
  focusCable(id){const layer=this.cableGroups.get(id);if(layer)this.map.fitBounds(layer.getBounds(),{padding:[40,45],maxZoom:8});}
  drawGrid(){this.grid.clearLayers();const bounds=this.map.getBounds();const zoom=this.map.getZoom();const step=zoom>=10?.25:zoom>=8.5?.5:1;let n=0;for(let lon=Math.ceil(bounds.getWest()/step)*step;lon<=bounds.getEast()&&n<45;lon+=step,n++){L.polyline([[bounds.getSouth(),lon],[bounds.getNorth(),lon]],{color:'#a7c9df',weight:.6,opacity:.22,dashArray:'3 7',interactive:false}).addTo(this.grid);L.marker([bounds.getNorth()-.08,lon],{icon:L.divIcon({html:lon.toFixed(2)+'°E',className:'coordinate-label',iconSize:[65,16],iconAnchor:[0,0]}),interactive:false}).addTo(this.grid);}n=0;for(let lat=Math.ceil(bounds.getSouth()/step)*step;lat<=bounds.getNorth()&&n<45;lat+=step,n++){L.polyline([[lat,bounds.getWest()],[lat,bounds.getEast()]],{color:'#a7c9df',weight:.6,opacity:.22,dashArray:'3 7',interactive:false}).addTo(this.grid);L.marker([lat,bounds.getWest()+.035],{icon:L.divIcon({html:lat.toFixed(2)+'°N',className:'coordinate-label',iconSize:[65,16],iconAnchor:[0,0]}),interactive:false}).addTo(this.grid);}}
  render(vessels,selected,time,gapThreshold=180){this.shipGroup.clearLayers();this.trackGroup.clearLayers();this.fixGroup.clearLayers();this.selectedPoint=null;
    vessels.forEach(v=>{const p=latestObservation(v,time);if(!p)return;const active=v.id===selected;const age=(time-p.ms)/60000;const stale=age>gapThreshold;const color=active?'#ffe0a1':v.ship_type==='漁船'?'#f2c97d':'#a2d3f8';const heading=p.heading??p.cog??0;
      const html=`<div class="ship-symbol" style="transform:rotate(${heading}deg)">${shipSVG(v.ship_type,color)}</div>${active?`<span class="ship-label">${esc(v.name)}</span>`:''}`;
      L.marker([p.lat,p.lon],{icon:L.divIcon({className:`ship-marker ${active?'selected':''} ${stale?'stale':''}`,html,iconSize:[32,42],iconAnchor:[16,21]}),title:`${v.name} · ${formatTime(p.ms)} · ${p.sog??'未知'} kn`,zIndexOffset:active?1000:0}).on('click',()=>this.onShip(v.id)).addTo(this.shipGroup);
      if(active){this.selectedPoint=p;L.circleMarker([p.lat,p.lon],{radius:29,color:'#ffe1a2',weight:1.4,opacity:.85,fillOpacity:.04,dashArray:stale?'4 5':null,interactive:false}).addTo(this.shipGroup);const points=v.points.filter(x=>x.ms<=time);gapSegments(points,gapThreshold).forEach(segment=>{if(segment.length>1)L.polyline(segment.map(p=>[p.lat,p.lon]),{color:'#ffe1a2',weight:2.4,opacity:.85}).bindTooltip('僅連接相鄰真實觀測；不代表連續定位').addTo(this.trackGroup);});points.forEach((point,i)=>L.circleMarker([point.lat,point.lon],{radius:3.8,color:'#fff0cb',weight:1,fillColor:'#efb963',fillOpacity:.75}).bindTooltip(`${esc(v.name)}<br>${formatTime(point.ms)}<br>SOG ${point.sog??'—'} kn · COG ${point.cog??'—'}°<br>第 ${point.source_row} 列 / ${esc(point.source_file)}`).addTo(this.fixGroup));}
    });
  }
  focusShip(){if(this.selectedPoint)this.map.setView([this.selectedPoint.lat,this.selectedPoint.lon],9,{animate:true});}
}
